on: workflow_dispatch
name: easychat_deployment_kubernetes

jobs:
    build-frontend:
      runs-on: ubuntu-latest
      steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to private registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.PRIVATE_REGISTRY_URL }}
          username: ${{ secrets.PRIVATE_REGISTRY_USER }}
          password: ${{ secrets.PRIVATE_REGISTRY_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./easychat-frontend/
          file: ./easychat-frontend/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: '${{ secrets.PRIVATE_REGISTRY_URL }}/easychat-frontend:latest'
    build-backend:
      runs-on: ubuntu-latest
      steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to private registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.PRIVATE_REGISTRY_URL }}
          username: ${{ secrets.PRIVATE_REGISTRY_USER }}
          password: ${{ secrets.PRIVATE_REGISTRY_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./easychat-backend/
          file: ./easychat-backend/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: '${{ secrets.PRIVATE_REGISTRY_URL }}/easychat-backend:latest'
    deployment:
      runs-on: ubuntu-latest
      needs:
      - build-backend
      - build-frontend
      steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Apply to Kubernetes-Cluster
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ${{ github.workspace }}/easychat-deployment.yaml