on: workflow_dispatch
name: easychat_deployment_kubernetes

jobs:
    build-fotnend:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Login to private registry
          uses: docker/login-action@v1
          with:
            registry: ${{ secrets.PRIVATE_REGISTRY_URL }}
            username: ${{ secrets.PRIVATE_REGISTRY_USER }}
            password: ${{ secrets.PRIVATE_REGISTRY_PASS }}
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./easychat-frontend/
            file: ./easychat-frontend/Dockerfile
            builder: ${{ steps.buildx.outputs.name }}
            push: true
            tags: '${{ secrets.PRIVATE_REGISTRY_URL }}/easychat-frontend:latest'